[pytest]
minversion = 7.0
addopts = --basetemp=.pytest --strict-markers
testpaths = ml_service/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::UserWarning
